### ISSUE TITLE
Spacing?

### ISSUE THREAD

**Issue by chuckhendo** [unumux/enterprise-css-standards#2]
On the formatting page, there is this:

```
Use tab indention
Tabs should equal 4 spaces
```

This is ambiguous. Tab indentation creates a single tab character (\t). 4 spaces creates 4 space characters ( ). I'm assuming the intention is to use 4 spaces for indentation. If that's the case, the first line should be removed.

**Comment by dbay24** [comment]
Updated formatting page to remove redundant line.
